# Generated by Django 5.2.6 on 2025-12-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0002_alter_contact_email_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
